<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>920c1269-2fe3-48b6-aa71-8e5d023f016b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_17</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/nav[1]/ul[1]/li[5]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'License Management')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>License Management</value>
        <webElementGuid>6d87a5e6-4e1f-4c34-8557-ff9a82d993a9</webElementGuid>
    </webElementProperties>
</WebElementEntity>