<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3c59c5e7-2bd9-46fd-b2c6-34a11ab91947</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_53</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[6]/div[3]/nav[1]/div[1]/ul[1]/a[9]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Manage your project settings.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Manage your project settings.</value>
        <webElementGuid>4ed97b43-bebc-4a00-b546-a5a301020f57</webElementGuid>
    </webElementProperties>
</WebElementEntity>