<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0fae3508-e078-4f78-9b48-557d3971b341</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[5]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Girish Kulkarni')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Girish Kulkarni</value>
        <webElementGuid>d5a61a8f-f7bd-4a7c-9298-6bfbbb0ce7f6</webElementGuid>
    </webElementProperties>
</WebElementEntity>