<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>39444cf8-f3a7-4a18-9a45-1ea5b600b5d0</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_56</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>