<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f3bc656-6353-4165-8b9d-7e24bd235f22</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_792</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[22]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>