<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>08b528ac-90b3-41a0-9577-80c788919ae7</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_7</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Download Katalon package')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Download Katalon package</value>
        <webElementGuid>578fc1d1-ba2e-464a-9e4b-e8eb23a3ea1a</webElementGuid>
    </webElementProperties>
</WebElementEntity>