<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8ca361d1-fdac-43a7-88a5-4f17e87b42b3</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>