<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ebc1d036-7a21-4499-9eeb-a17d1120771d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_64</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[27]/td[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'/Users/runner/work/katalon-platform-qengineer-automation/katalon-platform-qengineer-automation/Reports/20221007_225758/Change Password/20221007_225758/1665158344640.png')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>/Users/runner/work/katalon-platform-qengineer-automation/katalon-platform-qengineer-automation/Reports/20221007_225758/Change Password/20221007_225758/1665158344640.png</value>
        <webElementGuid>9f9b432d-cd94-47e8-a90c-858e1d33b1e1</webElementGuid>
    </webElementProperties>
</WebElementEntity>