<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f8bed865-bc46-4e4a-8ac1-c9dece8c4c97</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>