<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2642db4e-4b19-4aa0-b4ad-50e6d9d1f3be</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_10</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[3]/nav[1]/div[1]/ul[1]/a[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Update billing information.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Update billing information.</value>
        <webElementGuid>ffbe3d34-7b49-4f1b-9d89-c9a99cf96cb4</webElementGuid>
    </webElementProperties>
</WebElementEntity>