<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>92b1af30-380d-4aae-8514-8bd26324f489</elementGuidId>
    <imagePath></imagePath>
    <name>com_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/com-1password-button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>