<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6b8c568a-edf3-4002-ac4e-3f7148f02c7e</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_40</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/button[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Recent Work')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Recent Work</value>
        <webElementGuid>c5063943-84d1-49cc-9a42-a89feb632d6d</webElementGuid>
    </webElementProperties>
</WebElementEntity>