<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2ca0fbcc-44ba-4216-84f6-d9b2640f6151</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_330</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>